# Generated by Django 4.2.5 on 2023-12-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20, unique=True)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.CharField(max_length=20, unique=True)),
                ('material', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
